<?php
const STARTER_TEIJA = [
  'MU_Common_TeijaNauraa' => 1,
  'MU_Common_Hydracaena' => 1,
  'MU_Rare_Hydracaena' => 1,
  'MU_Common_SpindleHarvesters' => 1,
  'MU_Rare_SpindleHarvesters' => 2,
  'MU_Rare_TheSpindleMunaBastion' => 1,
  'MU_Common_TheSpindleMunaBastion' => 1,
  'MU_Common_SneezerShroom' => 1,
  'MU_Rare_SneezerShroom' => 2,
  'MU_Common_Dracaena' => 2,
  'MU_Rare_Dracaena' => 1,
  'MU_Rare_AloeVera' => 2,
  'MU_Common_MunaCaregiver' => 2,
  'MU_Rare_MunaCaregiver' => 1,
  'MU_Common_MunaDruid' => 1,
  'MU_Rare_MunaDruid' => 1,
  'MU_Common_MeditationTraining' => 2,
  'MU_Common_Nurture' => 2,
  'MU_Rare_Nurture' => 1,
  'MU_Rare_SapDuende' => 2,
  'MU_Common_Sustenance' => 3,
  'MU_Common_ManaReaping' => 2,
  'MU_Common_FloralTent' => 3,
  'MU_Rare_NewtonsLaw' => 1,
  'MU_Common_BountifulMeadow' => 3,
];
?>
