from __future__ import annotations

import argparse
import csv
import json
import os
import re
from dataclasses import dataclass
from pathlib import Path


AUTOGEN_BEGIN = "/* AUTOGENERATED extract-starter-decks BEGIN */"
AUTOGEN_END = "/* AUTOGENERATED extract-starter-decks END */"


SET_CODE_TO_NUM = {
    "CORE": 1,
    "ALIZE": 2,
    "BISE": 3,
    "CYCLONE": 4,
    "DUSTER": 5,
    "DUSTEROP": 5,
}


@dataclass(frozen=True)
class StarterDeck:
    author: str
    hero_label: str
    description: str
    cards_raw: str

    @property
    def hero_primary_name(self) -> str:
        # "Sierra & Oddball" -> "Sierra"
        base = self.hero_label.split("&", 1)[0].strip()
        return base or self.hero_label.strip()

    @property
    def hero_slug(self) -> str:
        # best-effort slug; keep it stable
        s = self.hero_primary_name.strip().lower()
        s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
        return s or "unknown_hero"

    @property
    def hero_const(self) -> str:
        return f"STARTER_{re.sub(r'[^A-Z0-9]+', '_', self.hero_primary_name.upper()).strip('_')}"


def parse_map_refs_classes(path: Path) -> dict[str, str]:
    """
    Parse `misc/map-refs-classnames.php` (const MAP_REFS_CLASSES = [ 'ID' => 'XX/XX_Common_Name', ... ])
    and return { card_id: class_name } where class_name is the portion after the slash.
    """
    text = path.read_text(encoding="utf-8", errors="replace")
    # Matches: 'ALT_CORE_B_AX_01_C' => 'AX/AX_Common_SierraOddball',
    pairs = re.findall(r"'([^']+)'\s*=>\s*'([^']+)'", text)
    out: dict[str, str] = {}
    for card_id, class_path in pairs:
        class_name = class_path.split("/", 1)[-1].strip()
        if class_name:
            out[card_id.strip()] = class_name
    return out


def parse_map_refs_classes_from_any_php(path: Path) -> dict[str, str]:
    """
    Parse any PHP file containing pairs like:
      'ALT_....' => 'XX/XX_Common_Something',
    and return { card_id: class_name } where class_name is the portion after the slash.
    """
    text = path.read_text(encoding="utf-8", errors="replace")
    pairs = re.findall(r"'([^']+)'\s*=>\s*'([^']+)'", text)
    out: dict[str, str] = {}
    for card_id, class_path in pairs:
        if not card_id.startswith("ALT_"):
            continue
        class_name = class_path.split("/", 1)[-1].strip()
        if class_name:
            out[card_id.strip()] = class_name
    return out


def parse_deck_cards(multiline: str) -> list[tuple[int, str]]:
    """
    CSV column "6. Cards" contains lines like:
      1 ALT_CORE_B_AX_01_C
      3 ALT_COREKS_B_AX_30_R1
    Returns list[(count, card_id)] in original order.
    """
    entries: list[tuple[int, str]] = []
    for raw_line in (multiline or "").splitlines():
        line = raw_line.strip()
        if not line:
            continue
        m = re.match(r"^(\d+)\s+([A-Z0-9_]+)$", line)
        if not m:
            raise ValueError(f"Unparseable deck card line: {raw_line!r}")
        entries.append((int(m.group(1)), m.group(2)))
    if not entries:
        raise ValueError("Empty deck card list")
    return entries


def normalize_card_id_for_lookup(card_id: str) -> list[str]:
    """
    Some exported decklists use alternate prefixes that map to the same underlying card.
    Return lookup candidates in priority order.
    """
    def to_core_uid(uid: str) -> str | None:
        # Mirrors Cards::getCoreUid for KS: only set code change.
        parts = uid.split("_")
        if len(parts) < 6:
            return None
        parts[1] = "CORE"
        return "_".join(parts)

    def to_main_uid(uid: str) -> str | None:
        # Mirrors Cards::getMainUid for alternate art / promo set codes.
        parts = uid.split("_")
        if len(parts) < 6:
            return None
        set_code = parts[1]
        try:
            num = int(parts[4])
        except Exception:
            num = None

        if set_code in {"DUSTEROP", "DUSTERCB", "DUSTERTOP"} and num is not None:
            if num < 25:
                parts[1] = "CORE"
            elif num < 45:
                parts[1] = "ALIZE"
            else:
                parts[1] = "DUSTER"
        elif set_code in {"TCS3"}:
            parts[1] = "BISE"
        elif set_code in {"WCQ25", "WCS25", "MUSUBI"}:
            parts[1] = "CORE"

        # Canonicalize art/promo marker to B
        parts[2] = "B"
        return "_".join(parts)

    candidates: list[str] = []

    def add(u: str | None) -> None:
        if u and u not in candidates:
            candidates.append(u)

    add(card_id)
    # Some lists use ALT_*_A_* vs ALT_*_B_*; mapping uses B for most canonical refs.
    add(card_id.replace("_A_", "_B_") if "_A_" in card_id else None)
    # KS set => CORE
    add(to_core_uid(card_id) if card_id.startswith("ALT_COREKS_") else None)
    # Promo/alt-art set codes => main uid
    add(to_main_uid(card_id))
    # Combine core conversion + main canonicalization
    if card_id.startswith("ALT_COREKS_"):
        add(to_main_uid(to_core_uid(card_id) or ""))

    return candidates


def infer_deck_set_number(hero_card_id: str) -> int:
    # e.g. ALT_CORE_B_AX_01_C => "CORE"
    m = re.match(r"^ALT_([A-Z0-9]+)_", hero_card_id)
    if not m:
        return 0
    return SET_CODE_TO_NUM.get(m.group(1), 0)


def infer_faction_lower(hero_card_id: str) -> str:
    # e.g. ALT_CORE_B_AX_01_C => "AX"
    parts = hero_card_id.split("_")
    if len(parts) >= 4:
        return parts[3].lower()
    return "xx"


def infer_hero_numeric_id(hero_card_id: str) -> int:
    # e.g. ALT_CORE_B_YZ_03_C => 3
    parts = hero_card_id.split("_")
    if len(parts) >= 5:
        try:
            return int(parts[4])
        except Exception:
            return 0
    return 0


def canonical_uid_for_lookup(card_id: str) -> str:
    """
    Return the first UID that exists in the mapping candidates list.
    Falls back to original card_id if nothing else.
    """
    cands = normalize_card_id_for_lookup(card_id)
    return cands[0] if cands else card_id


def build_deck_id(hero_card_id: str, hero_slug: str) -> str:
    faction = infer_faction_lower(hero_card_id)
    hero_num = infer_hero_numeric_id(hero_card_id)
    return f"{faction}_{hero_num}_{hero_slug}"

def render_php_include(const_name: str, card_counts_by_class: list[tuple[str, int]]) -> str:
    lines: list[str] = ["<?php", f"const {const_name} = ["]
    for class_name, count in card_counts_by_class:
        lines.append(f"  '{class_name}' => {count},")
    lines.append("];")
    lines.append("?>")
    lines.append("")
    return "\n".join(lines)


def ensure_js_file_with_markers(path: Path) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8", errors="replace")
    return "\n".join(
        [
            "// This file is partially autogenerated by misc/python-tools/extract-starter-decks.py",
            "",
            f"{AUTOGEN_BEGIN}",
            "// (generated content goes here)",
            f"{AUTOGEN_END}",
            "",
            "export const STARTER_DECKS = [];",
            "",
        ]
    )


def replace_between_markers(original: str, new_block: str) -> str:
    if AUTOGEN_BEGIN not in original or AUTOGEN_END not in original:
        # If file exists but lacks markers, append them at top to be safe.
        original = "\n".join(
            [
                AUTOGEN_BEGIN,
                "// (generated content goes here)",
                AUTOGEN_END,
                "",
                original.lstrip("\ufeff"),
            ]
        )
    pattern = re.compile(
        re.escape(AUTOGEN_BEGIN) + r"[\s\S]*?" + re.escape(AUTOGEN_END), re.MULTILINE
    )
    replacement = "\n".join([AUTOGEN_BEGIN, new_block.rstrip(), AUTOGEN_END])
    # Use a function replacement to avoid backslash escape handling (e.g. \uXXXX) in repl strings.
    return pattern.sub(lambda _m: replacement, original, count=1)


def main() -> int:
    repo_root = Path(__file__).resolve().parents[2]

    parser = argparse.ArgumentParser(
        description="Extract starter decks from starter-decks.csv into PHP include files and update modules/js/StarterDecks.js"
    )
    parser.add_argument(
        "--csv",
        default=str(repo_root / "starter-decks.csv"),
        help="Path to starter-decks.csv",
    )
    parser.add_argument(
        "--map",
        default=str(repo_root / "misc" / "map-refs-classnames.php"),
        help="Path to misc/map-refs-classnames.php",
    )
    parser.add_argument(
        "--map-fallback",
        default=str(repo_root / "modules" / "php" / "Cards" / "cards.inc.php"),
        help="Fallback mapping file (typically modules/php/Cards/cards.inc.php)",
    )
    parser.add_argument(
        "--php-out-dir",
        default=str(repo_root / "modules" / "php" / "Cards" / "StarterDecks"),
        help="Output directory for generated PHP includes",
    )
    parser.add_argument(
        "--js",
        default=str(repo_root / "modules" / "js" / "StarterDecks.js"),
        help="Path to modules/js/StarterDecks.js",
    )
    args = parser.parse_args()

    csv_path = Path(args.csv)
    map_path = Path(args.map)
    map_fallback_path = Path(args.map_fallback)
    php_out_dir = Path(args.php_out_dir)
    js_path = Path(args.js)

    # Prefer the dedicated mapping file, but fill any gaps from the full cards map.
    id_to_class = parse_map_refs_classes(map_path)
    if map_fallback_path.exists():
        fallback = parse_map_refs_classes_from_any_php(map_fallback_path)
        for k, v in fallback.items():
            id_to_class.setdefault(k, v)

    decks: list[StarterDeck] = []
    with csv_path.open("r", encoding="utf-8", errors="replace", newline="") as f:
        reader = csv.DictReader(f, delimiter=";")
        required = {"1. Name or Nickname", "3. Hero", "5. Deck Description  ", "6. Cards"}
        missing = required - set(reader.fieldnames or [])
        if missing:
            raise SystemExit(f"CSV missing expected columns: {sorted(missing)}")

        for row in reader:
            decks.append(
                StarterDeck(
                    author=(row.get("1. Name or Nickname") or "").strip(),
                    hero_label=(row.get("3. Hero") or "").strip(),
                    description=(row.get("5. Deck Description  ") or "").strip(),
                    cards_raw=(row.get("6. Cards") or "").strip(),
                )
            )

    php_out_dir.mkdir(parents=True, exist_ok=True)

    js_entries_by_faction: dict[str, list[str]] = {}

    for deck in decks:
        cards = parse_deck_cards(deck.cards_raw)
        hero_card_id_raw = cards[0][1]

        # Convert card IDs into class names
        class_counts: list[tuple[str, int]] = []
        for count, card_id in cards:
            cls = None
            for cid in normalize_card_id_for_lookup(card_id):
                cls = id_to_class.get(cid)
                if cls:
                    break
            if not cls:
                raise SystemExit(f"Missing card id mapping for {card_id} (hero={deck.hero_label})")
            class_counts.append((cls, count))

        # Use canonical hero UID for deck identity so COREKS/alt-art decks name consistently.
        hero_card_id = None
        for cid in normalize_card_id_for_lookup(hero_card_id_raw):
            if cid in id_to_class:
                hero_card_id = cid
                break
        hero_card_id = hero_card_id or hero_card_id_raw

        deck_id = build_deck_id(hero_card_id, deck.hero_slug)
        php_filename = f"{deck_id}.inc.php"
        php_path = php_out_dir / php_filename
        php_path.write_text(render_php_include(deck.hero_const, class_counts), encoding="utf-8")

        faction_key = infer_faction_lower(hero_card_id).upper()
        js_entries_by_faction.setdefault(faction_key, []).append(
            "    {"
            f' deckId: "{deck_id}",'
            f' hero: "{deck.hero_label}",'
            f' author: "{deck.author}",'
            f" description: {json.dumps(deck.description)}"
            " },"
        )

    faction_lines: list[str] = []
    for faction_key in sorted(js_entries_by_faction.keys()):
        faction_lines.append(f'  "{faction_key}": [')
        faction_lines.extend(js_entries_by_faction[faction_key])
        faction_lines.append("  ],")

    js_generated = "\n".join(
        [
            "  const STARTER_DECK_META = {",
            *faction_lines,
            "  };",
            "",
        ]
    )

    js_original = ensure_js_file_with_markers(js_path)
    js_updated = replace_between_markers(js_original, js_generated)
    js_path.write_text(js_updated, encoding="utf-8")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
